# Generated by Django 4.2.16 on 2024-12-06 14:40

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model("project", "Category")
    categories_to_create = [Category(name=name) for name in category_names]
    Category.objects.bulk_create(categories_to_create)


def remove_all_categories(apps, schema_editor):
    Category = apps.get_model("project", "Category")
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_like_unique_like_per_post_and_more"),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_code=remove_all_categories),
    ]


category_names = (
    "Art & Design",
    "Photography",
    "Food & Beverages",
    "Fashion & Style",
    "Beauty & Cosmetics",
    "Home Décor & Interior Design",
    "DIY & Crafts",
    "Technology & Gadgets",
    "Travel & Destinations",
    "Health & Fitness",
    "Weddings & Events",
    "Parenting & Family",
    "Animals & Pets",
    "Automotive",
    "Outdoors & Adventure",
    "Books & Literature",
    "Movies & Television",
    "Music",
    "Gaming",
    "Finance & Investing",
    "Business & Entrepreneurship",
    "Spirituality & Religion",
    "Holidays & Celebrations",
    "Science & Education",
    "History & Culture",
    "Architecture & Urban Design",
    "Humor & Memes",
    "Sports & Athletics",
    "Quotes & Inspiration",
    "Personal Development & Life Hacks",
)
